backend:
  name: auth0
  domain: "${AUTH0_DOMAIN}"        # Auth0 Tenant Domain
  client_id: "${AUTH0_CLIENT_ID}"  # Auth0 Application Client ID
  branch: main                     # Default branch to commit content

media_folder: "concepts/assets"    # Where uploaded media will be stored in the repo
public_folder: "/concepts/assets"  # Path used on the site

collections:
  - name: "concepts"
    label: "Concepts"
    folder: "concepts/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown", required: true }
      - label: "Related Concepts"
        name: "related"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Quick Quiz"
        name: "quiz"
        widget: "list"
        fields:
          - { label: "Question", name: "question", widget: "string" }
          - { label: "Answer", name: "answer", widget: "text" }
      - label: "Resources"
        name: "resources"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
